### ISSUE TITLE
What is mean the field 'Data source (Page-ID)' and for what it?

### ISSUE THREAD

**Issue by typo3ua** [ifabrik-GmbH/ifab_realestate#10]
Hi!
I try to understand how does work your extension... having come across a field 'Data source (Page-ID)' I can not understand what is that and for what it?

![Data_source_Page-ID](https://user-images.githubusercontent.com/638022/81194932-df8b5080-8fc5-11ea-890b-4b68c059e285.png)

Please! Can you explain to me it?
Thank you in advance.

**Comment by ifabrik-GmbH** [comment]
In case you have not filled the constant `persistence.storagePid` or you want to override it, you can use that to define from which folder should the extension get the data from. It is simillar to the Record Storage Page but more reliable since the `settings.persistence.storagePid` is defined for this field.

**Comment by typo3ua** [comment]
Thank you for your reply.
